openapi: 3.0.0
info:
  title: Farcaster Agent API
  description: API for an agent that analyzes Farcaster data and generates transaction payloads for relevant buy opportunities.
  version: 1.0.0
servers:
  - url: http://0.0.0.0:5555
paths:
  /api:
    get:
      summary: Returns the main HTML page
      responses:
        '200':
          description: HTML response
          content:
            text/html:
              schema:
                type: string
  /api/analyze:
    post:
      summary: Analyze Farcaster data for search results
      description: Analyzes Farcaster posts based on the specified parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequest'  # Reference to schema defined below
      responses:
        '200':
          description: Successful analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'  # Reference to schema defined below
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Explanation of the error (e.g., missing `query`)

components:
  schemas:
    AnalyzeRequest:
      x-persistent: true  # Marking the schema as persistent
      type: object
      properties:
        walletAddress:
          type: string
          description: The unique wallet address of the user.
        count:
          type: integer
          description: Optional count value associated with the user.
          nullable: true
        text:
          type: string
          description: Optional text (e.g., a post or message).
          nullable: true
        engagement:
          type: string  # Change engagement to a simple string in the request body
          description: Optional engagement data (e.g., "100 reactions, 5 recasts").
          nullable: true
      required:
        - walletAddress  # walletAddress is mandatory for the request
